version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "gradle"
        versions: [">= 9.1.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
