---
commitizen:
  annotated_tag: true
  bump_message: "release $current_version \u2192 $new_version"
  major_version_zero: true
  name: cz_conventional_commits
  tag_format: $version
  version: 0.1.0-rc4
  version_files:
  - build.gradle.kts
  version_scheme: semver
