[versions]
kotlin = "2.3.20"
spotless = "8.4.0"
kotest = "6.1.9"
ktfmt = "0.53"
com-vanniktech-maven-publish = "0.36.0"
dokka = "2.2.0"
kover = "0.9.8"
sonarqube = "7.2.3.7755"
kotlin-logging = "8.0.01"
slf4j = "2.0.17"
kotlinx-benchmark = "0.4.16"

[libraries]
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
kotlinx-benchmark-runtime = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "kotlinx-benchmark" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "com-vanniktech-maven-publish" }
dokka-html = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
sonarqube = { id = "org.sonarqube", version.ref= "sonarqube"}
kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinx-benchmark" }