name: Continuous Integration

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Continuous Integration

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            /*.gradle*
            /**/*.gradle*
            /**/gradle-wrapper.properties
            /gradle/libs.versions.toml

      - name: Format code
        run: ./gradlew spotlessCheck

      - name: Build and test
        run: ./gradlew build

      - name: JVM tests
        run: ./gradlew jvmTest

      - name: JS tests
        run: ./gradlew jsTest

