name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

permissions:
    contents: read
    pull-requests: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Continuous Integration

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties
            **/gradle/libs.versions.toml

      - name: Test Code Style
        run: ./gradlew spotlessCheck

      - name: JVM tests
        run: ./gradlew jvmTest

      - name: JS tests
        run: ./gradlew jsTest
