name: Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

concurrency:
  group: "publish"
  cancel-in-progress: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties
            **/gradle/libs.versions.toml

      - name: Test Code Style
        run: ./gradlew spotlessCheck

      - name: JVM tests
        run: ./gradlew jvmTest

      - name: JS tests
        run: ./gradlew jsTest

  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties
            **/gradle/libs.versions.toml

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to Maven Central
        run: ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}

  publish-gh-pages:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - publish
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties
            **/gradle/libs.versions.toml

      - name: Build documentation with Gradle
        run: ./gradlew dokkaGeneratePublicationHtml

      - name: Upload documentation artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/dokka/html'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Copy to docs
        run: |
          rm -rf docs/dokka/
          mkdir -p docs/dokka/${{github.ref_name}}
          cp -r build/dokka/html/* docs/dokka/${{github.ref_name}}/

      - name: Commit and push changes to current branch
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/dokka/${{github.ref_name}}
          git commit -m "Update documentation for ${{github.ref_name}}"
          git push